job:
  date: 2024-06-19
  start_time: 16-41-40
  details:
    model_name: Llama-2-70b-chat-hf
    batch_size: 32
    hf_name: /lcrc/project/ECP-EZ/ac.gwilkins/models--meta-llama--Llama-2-70b-chat-hf/snapshots/e9149a12809580e8602995856f8098ce973d1080
    num_gpus: 2
    dataset: orca
